// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Lexer.flex

import compilerTools.Token;
import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int EXPECT_COLOR = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\6\0\1\5\2\0\1\6\1\0\1\7\1\10\1\0"+
    "\1\11\12\12\1\0\1\13\2\0\1\14\2\0\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\2\23\1\24\2\23"+
    "\1\25\1\23\1\26\1\27\1\30\2\23\1\31\1\32"+
    "\6\23\1\33\1\0\1\34\1\0\1\35\1\0\1\36"+
    "\1\37\1\40\1\41\1\42\1\23\1\43\1\23\1\44"+
    "\1\45\1\23\1\46\1\47\1\50\1\51\2\23\1\52"+
    "\1\53\1\54\1\55\1\56\2\23\1\57\1\60\1\61"+
    "\1\0\1\62\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\2\1\1\5\1\6"+
    "\6\7\1\10\1\11\1\12\1\13\2\14\1\15\11\16"+
    "\1\17\1\0\1\2\1\20\10\7\14\16\1\0\1\21"+
    "\1\22\7\7\15\16\6\7\1\23\1\16\1\24\6\16"+
    "\3\7\1\25\1\26\1\7\3\16\3\7\1\27\1\16"+
    "\1\7\1\30\1\31\1\32";

  private static int [] zzUnpackAction() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\146\0\231\0\146\0\146\0\314"+
    "\0\377\0\u0132\0\146\0\u0165\0\u0198\0\u01cb\0\u01fe\0\u0231"+
    "\0\u0264\0\146\0\146\0\146\0\146\0\146\0\377\0\146"+
    "\0\u0297\0\u02ca\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc"+
    "\0\u042f\0\146\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e\0\u0561"+
    "\0\u0594\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0693\0\u06c6\0\u06f9"+
    "\0\u072c\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u085e\0\u0891"+
    "\0\u08c4\0\u08f7\0\u0198\0\u0198\0\u092a\0\u095d\0\u0990\0\u09c3"+
    "\0\u09f6\0\u0a29\0\u0a5c\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b"+
    "\0\u0b8e\0\u0bc1\0\u0bf4\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3"+
    "\0\u0d26\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25\0\u0198\0\u0e58"+
    "\0\u0297\0\u0e8b\0\u0ebe\0\u0ef1\0\u0f24\0\u0f57\0\u0f8a\0\u0fbd"+
    "\0\u0ff0\0\u1023\0\u0198\0\u0198\0\u1056\0\u1089\0\u10bc\0\u10ef"+
    "\0\u1122\0\u1155\0\u1188\0\u0198\0\u11bb\0\u11ee\0\u0198\0\u0198"+
    "\0\u0198";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\5\1\6\1\3\1\7\1\10"+
    "\1\11\1\12\1\13\1\3\1\14\3\15\1\16\1\17"+
    "\1\15\1\20\5\15\1\21\1\22\1\23\1\3\23\15"+
    "\1\24\1\25\1\26\2\4\1\0\1\5\4\26\1\27"+
    "\1\26\1\30\1\26\16\31\3\26\1\32\1\33\1\34"+
    "\2\31\1\35\3\31\1\36\1\37\1\31\1\40\3\31"+
    "\1\41\2\31\2\26\65\0\1\4\74\0\1\42\54\0"+
    "\1\43\2\0\1\44\63\0\1\12\2\0\16\45\3\0"+
    "\23\45\14\0\1\15\2\0\5\15\1\46\2\15\1\47"+
    "\5\15\2\0\24\15\14\0\1\15\2\0\16\15\2\0"+
    "\24\15\14\0\1\15\2\0\13\15\1\50\1\51\1\15"+
    "\2\0\24\15\14\0\1\15\2\0\7\15\1\52\2\15"+
    "\1\53\3\15\2\0\24\15\14\0\1\15\2\0\11\15"+
    "\1\54\4\15\2\0\24\15\14\0\1\15\2\0\7\15"+
    "\1\55\6\15\2\0\24\15\14\0\1\31\2\0\16\31"+
    "\2\0\24\31\14\0\1\31\2\0\16\31\2\0\12\31"+
    "\1\56\10\31\1\57\14\0\1\31\2\0\16\31\2\0"+
    "\11\31\1\60\12\31\14\0\1\31\2\0\16\31\2\0"+
    "\22\31\1\61\1\31\14\0\1\31\2\0\16\31\2\0"+
    "\15\31\1\62\6\31\14\0\1\31\2\0\16\31\2\0"+
    "\1\31\1\63\12\31\1\64\7\31\14\0\1\31\2\0"+
    "\16\31\2\0\1\31\1\65\3\31\1\66\16\31\14\0"+
    "\1\31\2\0\16\31\2\0\14\31\1\67\7\31\14\0"+
    "\1\31\2\0\16\31\2\0\5\31\1\70\1\31\1\71"+
    "\14\31\2\0\6\43\1\72\54\43\2\44\1\4\1\44"+
    "\1\5\56\44\12\0\1\45\2\0\16\45\2\0\24\45"+
    "\14\0\1\15\2\0\3\15\1\73\5\15\1\74\4\15"+
    "\2\0\24\15\14\0\1\15\2\0\5\15\1\75\10\15"+
    "\2\0\24\15\14\0\1\15\2\0\14\15\1\76\1\15"+
    "\2\0\24\15\14\0\1\15\2\0\15\15\1\77\2\0"+
    "\24\15\14\0\1\15\2\0\11\15\1\100\4\15\2\0"+
    "\24\15\14\0\1\15\2\0\11\15\1\101\4\15\2\0"+
    "\24\15\14\0\1\15\2\0\7\15\1\102\6\15\2\0"+
    "\24\15\14\0\1\15\2\0\13\15\1\103\2\15\2\0"+
    "\24\15\14\0\1\31\2\0\16\31\2\0\1\31\1\104"+
    "\22\31\14\0\1\31\2\0\16\31\2\0\20\31\1\105"+
    "\3\31\14\0\1\31\2\0\16\31\2\0\1\31\1\106"+
    "\22\31\14\0\1\31\2\0\16\31\2\0\1\31\1\107"+
    "\22\31\14\0\1\31\2\0\16\31\2\0\7\31\1\110"+
    "\14\31\14\0\1\31\2\0\16\31\2\0\15\31\1\111"+
    "\6\31\14\0\1\31\2\0\16\31\2\0\15\31\1\112"+
    "\6\31\14\0\1\31\2\0\16\31\2\0\15\31\1\113"+
    "\6\31\14\0\1\31\2\0\16\31\2\0\6\31\1\114"+
    "\15\31\14\0\1\31\2\0\16\31\2\0\10\31\1\115"+
    "\5\31\1\116\5\31\14\0\1\31\2\0\16\31\2\0"+
    "\15\31\1\117\6\31\14\0\1\31\2\0\16\31\2\0"+
    "\14\31\1\120\7\31\2\0\6\43\1\72\2\43\1\4"+
    "\51\43\12\0\1\15\2\0\1\121\15\15\2\0\24\15"+
    "\14\0\1\15\2\0\7\15\1\122\6\15\2\0\24\15"+
    "\14\0\1\15\2\0\1\123\15\15\2\0\24\15\14\0"+
    "\1\15\2\0\1\124\15\15\2\0\24\15\14\0\1\15"+
    "\2\0\3\15\1\125\12\15\2\0\24\15\14\0\1\15"+
    "\2\0\2\15\1\126\13\15\2\0\24\15\14\0\1\15"+
    "\2\0\12\15\1\127\3\15\2\0\24\15\14\0\1\31"+
    "\2\0\16\31\2\0\15\31\1\130\6\31\14\0\1\31"+
    "\2\0\16\31\2\0\11\31\1\131\12\31\14\0\1\31"+
    "\2\0\16\31\2\0\13\31\1\132\10\31\14\0\1\31"+
    "\2\0\16\31\2\0\13\31\1\131\10\31\14\0\1\31"+
    "\2\0\16\31\2\0\16\31\1\131\5\31\14\0\1\31"+
    "\2\0\16\31\2\0\15\31\1\133\6\31\14\0\1\31"+
    "\2\0\16\31\2\0\1\31\1\134\22\31\14\0\1\31"+
    "\2\0\16\31\2\0\1\31\1\135\22\31\14\0\1\31"+
    "\2\0\16\31\2\0\15\31\1\115\6\31\14\0\1\31"+
    "\2\0\16\31\2\0\14\31\1\131\7\31\14\0\1\31"+
    "\2\0\16\31\2\0\1\31\1\131\22\31\14\0\1\31"+
    "\2\0\16\31\2\0\4\31\1\136\17\31\14\0\1\31"+
    "\2\0\16\31\2\0\11\31\1\137\12\31\14\0\1\15"+
    "\2\0\1\15\1\140\14\15\2\0\24\15\14\0\1\15"+
    "\2\0\10\15\1\141\5\15\2\0\24\15\14\0\1\15"+
    "\2\0\3\15\1\142\12\15\2\0\24\15\14\0\1\15"+
    "\2\0\10\15\1\143\5\15\2\0\24\15\14\0\1\15"+
    "\2\0\12\15\1\144\3\15\2\0\24\15\14\0\1\15"+
    "\2\0\7\15\1\145\6\15\2\0\24\15\14\0\1\31"+
    "\2\0\16\31\2\0\7\31\1\146\14\31\14\0\1\31"+
    "\2\0\16\31\2\0\3\31\1\115\20\31\14\0\1\31"+
    "\2\0\16\31\2\0\14\31\1\107\7\31\14\0\1\31"+
    "\2\0\16\31\2\0\4\31\1\115\17\31\14\0\1\31"+
    "\2\0\16\31\2\0\13\31\1\147\10\31\14\0\1\31"+
    "\2\0\16\31\2\0\5\31\1\131\16\31\14\0\1\31"+
    "\2\0\16\31\2\0\5\31\1\150\16\31\14\0\1\15"+
    "\2\0\4\15\1\151\11\15\2\0\24\15\14\0\1\15"+
    "\2\0\12\15\1\152\3\15\2\0\24\15\14\0\1\15"+
    "\2\0\12\15\1\153\3\15\2\0\24\15\14\0\1\15"+
    "\2\0\12\15\1\154\3\15\2\0\24\15\14\0\1\31"+
    "\2\0\16\31\2\0\11\31\1\155\12\31\14\0\1\31"+
    "\2\0\16\31\2\0\10\31\1\116\13\31\14\0\1\31"+
    "\2\0\16\31\2\0\17\31\1\116\4\31\14\0\1\15"+
    "\2\0\15\15\1\156\2\0\24\15\14\0\1\15\2\0"+
    "\11\15\1\157\4\15\2\0\24\15\14\0\1\15\2\0"+
    "\14\15\1\160\1\15\2\0\24\15\14\0\1\31\2\0"+
    "\16\31\2\0\11\31\1\115\12\31\14\0\1\15\2\0"+
    "\12\15\1\161\3\15\2\0\24\15\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4641];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\1\1\2\11\3\1\1\11\6\1\5\11"+
    "\1\1\1\11\11\1\1\11\1\0\26\1\1\0\67\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    /**
     * Crea un Token interno y lo envuelve en un Symbol de CUP.
     * symCode debe coincidir exactamente con el nombre del terminal en sym.java.
     */
    private Symbol token(String lexeme, String lexicalComp, int line, int column, int symCode) {
        Token t = new Token(lexeme, lexicalComp, line + 1, column + 1);
        return new Symbol(symCode, t);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "ERROR_LEXICO", yyline, yycolumn, sym.error);
            }
          // fall through
          case 27: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 28: break;
          case 3:
            { return token(yytext(), "COMILLA_SIMPLE",yyline, yycolumn, sym.COMILLA_SIMPLE);
            }
          // fall through
          case 29: break;
          case 4:
            { return token(yytext(), "COMA",          yyline, yycolumn, sym.COMA);
            }
          // fall through
          case 30: break;
          case 5:
            { return token(yytext(), "ERROR_DIGIT",       yyline, yycolumn, sym.error);
            }
          // fall through
          case 31: break;
          case 6:
            { return token(yytext(), "PUNTO_Y_COMA",  yyline, yycolumn, sym.PUNTO_Y_COMA);
            }
          // fall through
          case 32: break;
          case 7:
            { return token(yytext(), "IDENTIFICADOR", yyline, yycolumn, sym.IDENTIFICADOR);
            }
          // fall through
          case 33: break;
          case 8:
            { return token(yytext(), "CORCHETE_IZQ",  yyline, yycolumn, sym.CORCHETE_IZQ);
            }
          // fall through
          case 34: break;
          case 9:
            { return token(yytext(), "CORCHETE_DER",  yyline, yycolumn, sym.CORCHETE_DER);
            }
          // fall through
          case 35: break;
          case 10:
            { return token(yytext(), "LLAVE_IZQ",     yyline, yycolumn, sym.LLAVE_IZQ);
            }
          // fall through
          case 36: break;
          case 11:
            { return token(yytext(), "LLAVE_DER",     yyline, yycolumn, sym.LLAVE_DER);
            }
          // fall through
          case 37: break;
          case 12:
            { yybegin(YYINITIAL); return token(yytext(), "ERROR_LEXICO", yyline, yycolumn, sym.error);
            }
          // fall through
          case 38: break;
          case 13:
            { yybegin(YYINITIAL); return token(yytext(), "PUNTO_Y_COMA", yyline, yycolumn, sym.PUNTO_Y_COMA);
            }
          // fall through
          case 39: break;
          case 14:
            { yybegin(YYINITIAL); return token(yytext(), "ERROR_COLOR", yyline, yycolumn, sym.error);
            }
          // fall through
          case 40: break;
          case 15:
            { return token(yytext(), "FLECHA",        yyline, yycolumn, sym.FLECHA);
            }
          // fall through
          case 41: break;
          case 16:
            { return token(yytext(), "ERROR_DIGIT_IDENT", yyline, yycolumn, sym.error);
            }
          // fall through
          case 42: break;
          case 17:
            { return token(yytext(), "AFD",     yyline, yycolumn, sym.AFD);
            }
          // fall through
          case 43: break;
          case 18:
            { return token(yytext(), "AFN",     yyline, yycolumn, sym.AFN);
            }
          // fall through
          case 44: break;
          case 19:
            { return token(yytext(), "TIPO",     yyline, yycolumn, sym.TIPO);
            }
          // fall through
          case 45: break;
          case 20:
            { yybegin(YYINITIAL); return token(yytext(), "COLOR", yyline, yycolumn, sym.COLOR);
            }
          // fall through
          case 46: break;
          case 21:
            { return token(yytext(), "FINAL",    yyline, yycolumn, sym.FINAL);
            }
          // fall through
          case 47: break;
          case 22:
            { yybegin(EXPECT_COLOR); return token(yytext(), "FONDO", yyline, yycolumn, sym.FONDO);
            }
          // fall through
          case 48: break;
          case 23:
            { return token(yytext(), "INICIO",   yyline, yycolumn, sym.INICIO);
            }
          // fall through
          case 49: break;
          case 24:
            { return token(yytext(), "EPSILON", yyline, yycolumn, sym.EPSILON);
            }
          // fall through
          case 50: break;
          case 25:
            { return token(yytext(), "ESTADOS",  yyline, yycolumn, sym.ESTADOS);
            }
          // fall through
          case 51: break;
          case 26:
            { return token(yytext(), "ALFABETO", yyline, yycolumn, sym.ALFABETO);
            }
          // fall through
          case 52: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
