/* Parser.cup actualizado */

import java.util.ArrayList;
import java.util.List;
import compilerTools.ErrorLSSL;
import compilerTools.Token;
import compilerTools.ASTNode;
import java_cup.runtime.*;

/* ====================== Bloque parser code ====================== */
parser code {:
    public List<ErrorLSSL> errors = new ArrayList<>();
    public List<SimboloDSL> symbols = new ArrayList<>(); //  LISTA DE SIMBOLOS
    
    private Token tokenAnterior = null;
    private Token tokenActual = null;

    @Override
    public Symbol scan() throws java.lang.Exception {
        Symbol sym = super.scan();
        if (sym != null && sym.value instanceof Token) {
            tokenAnterior = tokenActual;
            tokenActual = (Token) sym.value;
        }
        return sym;
    }

    // Método para registrar símbolos en la tabla
    public void addSymbol(String name, String type, Token t) {
        symbols.add(new SimboloDSL(name, type, t.getLine(), t.getColumn()));
    }

    public void syntax_error(Symbol s) {
        Token t = (Token) s.value;
        if (t != null) {
            String lexema = t.getLexeme();
            
            if (tokenAnterior != null) {
                String descripcion = "[SinError 010] Error Sintáctico: Token inesperado '" + lexema + "'. ¿Falta un punto y coma (;) justo después de '" + tokenAnterior.getLexeme() + "'?";
                Token tokenAjustado = new Token(lexema, t.getLexicalComp(), tokenAnterior.getLine(), tokenAnterior.getColumn());
                errors.add(new ErrorLSSL(1, descripcion, tokenAjustado));
            } else {
                String descripcion = "[SinError 010] Error Sintáctico: Token inesperado '" + lexema + "'";
                errors.add(new ErrorLSSL(1, descripcion, t));
            }
        }
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        Token t = (Token) s.value;
        if (t != null) {
            String descripcion = "[SinError 011] Error Fatal: No se pudo recuperar del error cerca de '" + t.getLexeme() + "'. Revisa la estructura general.";
            errors.add(new ErrorLSSL(1, descripcion, t));
        } else {
            Token dummyToken = new Token("EOF", "FIN_ARCHIVO", 0, 0);
            errors.add(new ErrorLSSL(1, "[SinError 011] Error Fatal: Fin de archivo inesperado. ¿Falta cerrar llaves o un punto y coma?", dummyToken));
        }
    }
:};

/* ====================== 1) DECLARACIÓN DE TERMINALES ====================== */
terminal TIPO, ALFABETO, INICIO, FINAL, ESTADO;
terminal EPSILON, FONDO, AFD, AFN;
terminal FLECHA, CORCHETE_IZQ, CORCHETE_DER, LLAVE_IZQ, LLAVE_DER;
terminal COMILLA_SIMPLE, PUNTO_Y_COMA, COMA;
terminal IDENTIFICADOR;

/* ====================== 2) DECLARACIÓN DE NO TERMINALES ====================== */
non terminal ASTNode Program, StatementList, Statement;
non terminal ASTNode ConfigType, AlphabetDef, Transition, StartDef, FinalDef, StateDef, BackgroundDef;
non terminal ASTNode SymbolList, StateList, SymbolVal;

/* ====================== 3) SÍMBOLO INICIAL ====================== */
start with Program;

/* ====================== 4) PRODUCCIONES ====================== */

Program ::= StatementList:sl
    {: 
        ASTNode node = new ASTNode("AutoDraw_DSL");
        node.addChild(sl);
        RESULT = node;
    :};

StatementList ::= 
    StatementList:sl Statement:s
    {: 
        sl.addChild(s);
        RESULT = sl;
    :}
    | Statement:s
    {:
        ASTNode node = new ASTNode("Sentencias");
        node.addChild(s);
        RESULT = node;
    :};

Statement ::= 
    ConfigType:c    {: RESULT = c; :}
    | AlphabetDef:a {: RESULT = a; :}
    | Transition:t  {: RESULT = t; :}
    | StartDef:s    {: RESULT = s; :}
    | FinalDef:f    {: RESULT = f; :}
    | StateDef:st   {: RESULT = st; :}
    | BackgroundDef:b {: RESULT = b; :}
    | error PUNTO_Y_COMA
    {:
        RESULT = new ASTNode("Sentencia_Ignorada_Por_Error");
    :}
    ;

ConfigType ::= TIPO AFD:a PUNTO_Y_COMA
    {: 
        parser.addSymbol("AFD", "Tipo de Autómata", (Token)a);
        RESULT = new ASTNode("Config: TIPO AFD"); 
    :}
    | TIPO AFN:a PUNTO_Y_COMA
    {: 
        parser.addSymbol("AFN", "Tipo de Autómata", (Token)a);
        RESULT = new ASTNode("Config: TIPO AFN"); 
    :}
    | TIPO error PUNTO_Y_COMA
    {: 
        Token t = (Token) ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
        parser.errors.add(new ErrorLSSL(1, "[SinError 012] Sugerencia: Después de 'TIPO' solo se admite 'AFD' o 'AFN'. Ejemplo: TIPO AFD;", t));
        RESULT = new ASTNode("Error_En_Tipo"); 
    :};

AlphabetDef ::= ALFABETO LLAVE_IZQ SymbolList:sl LLAVE_DER PUNTO_Y_COMA
    {: 
        ASTNode node = new ASTNode("Definición_Alfabeto");
        node.addChild(sl);
        RESULT = node;
    :}
    | ALFABETO error PUNTO_Y_COMA
    {:
        Token t = (Token) ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
        parser.errors.add(new ErrorLSSL(1, "[SinError 013] Sugerencia: El ALFABETO debe ir entre llaves y separado por comas. Ejemplo: ALFABETO { 'a', 'b' };", t));
        RESULT = new ASTNode("Error_En_Alfabeto");
    :};

SymbolList ::= 
    SymbolList:sl COMA SymbolVal:s
    {:
        sl.addChild(s);
        RESULT = sl;
    :}
    | SymbolVal:s
    {:
        ASTNode node = new ASTNode("Lista_Simbolos");
        node.addChild(s);
        RESULT = node;
    :};

SymbolVal ::= COMILLA_SIMPLE IDENTIFICADOR:id COMILLA_SIMPLE
    {: 
        Token t = (Token)id;
        parser.addSymbol(t.getLexeme(), "Símbolo Alfabeto", t);
        RESULT = new ASTNode("Simbolo: " + t.getLexeme());
    :}
    | EPSILON:e
    {: 
        parser.addSymbol("ε", "Símbolo Épsilon", (Token)e);
        RESULT = new ASTNode("Simbolo: EPSILON"); 
    :};

StartDef ::= INICIO IDENTIFICADOR:id PUNTO_Y_COMA
    {:
        Token t = (Token)id;
        parser.addSymbol(t.getLexeme(), "Estado Inicial", t);
        RESULT = new ASTNode("Estado_Inicial: " + t.getLexeme());
    :};

FinalDef ::= FINAL StateList:sl PUNTO_Y_COMA
    {:
        ASTNode node = new ASTNode("Estados_Finales");
        node.addChild(sl);
        RESULT = node;
    :};

StateList ::= 
    StateList:sl COMA IDENTIFICADOR:id
    {:
        Token t = (Token)id;
        parser.addSymbol(t.getLexeme(), "Estado Final", t);
        sl.addChild(new ASTNode(t.getLexeme()));
        RESULT = sl;
    :}
    | IDENTIFICADOR:id
    {:
        Token t = (Token)id;
        parser.addSymbol(t.getLexeme(), "Estado Final", t);
        ASTNode node = new ASTNode("Lista_Estados");
        node.addChild(new ASTNode(t.getLexeme()));
        RESULT = node;
    :};

Transition ::= IDENTIFICADOR:origen FLECHA IDENTIFICADOR:destino CORCHETE_IZQ SymbolVal:sv CORCHETE_DER PUNTO_Y_COMA
    {:
        Token tOri = (Token) ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
        Token tDes = (Token) ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
        ASTNode node = new ASTNode("Transicion");
        node.addChild(new ASTNode("Origen: " + tOri.getLexeme()));
        node.addChild(new ASTNode("Destino: " + tDes.getLexeme()));
        node.addChild(sv);
        RESULT = node;
    :}
    | IDENTIFICADOR:origen FLECHA IDENTIFICADOR:destino error PUNTO_Y_COMA
    {:
        Token tOri = (Token) ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
        parser.errors.add(new ErrorLSSL(1, "[SinError 014] Sugerencia: Transición mal formada. Asegúrate de usar corchetes para el símbolo. Ejemplo: " + tOri.getLexeme() + " -> destino ['a'];", tOri));
        RESULT = new ASTNode("Error_En_Transicion");
    :};

StateDef ::= ESTADO IDENTIFICADOR:id PUNTO_Y_COMA
    {:
        Token t = (Token)id;
        parser.addSymbol(t.getLexeme(), "Estado Declarado", t);
        RESULT = new ASTNode("Declarar_Estado: " + t.getLexeme());
    :};

BackgroundDef ::= FONDO IDENTIFICADOR:id PUNTO_Y_COMA
    {:
        Token t = (Token)id;
        parser.addSymbol(t.getLexeme(), "Color Fondo", t);
        RESULT = new ASTNode("Color_Fondo: " + t.getLexeme());
    :};