
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java.util.ArrayList;
import java.util.List;
import compilerTools.ErrorLSSL;
import compilerTools.Token;
import compilerTools.ASTNode;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\050\000\002\002\004\000\002\002\006\000\002\002" +
    "\004\000\002\003\004\000\002\003\005\000\002\003\003" +
    "\000\002\007\005\000\002\007\005\000\002\007\005\000" +
    "\002\010\007\000\002\010\005\000\002\016\005\000\002" +
    "\016\003\000\002\020\005\000\002\020\003\000\002\004" +
    "\004\000\002\004\003\000\002\004\003\000\002\022\004" +
    "\000\002\022\003\000\002\012\005\000\002\012\005\000" +
    "\002\014\005\000\002\014\005\000\002\005\003\000\002" +
    "\005\002\000\002\023\004\000\002\023\003\000\002\011" +
    "\011\000\002\011\007\000\002\021\005\000\002\021\003" +
    "\000\002\006\003\000\002\006\003\000\002\013\005\000" +
    "\002\013\005\000\002\017\005\000\002\017\003\000\002" +
    "\015\005\000\002\015\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\116\000\006\003\006\004\010\001\002\000\004\002" +
    "\120\001\002\000\006\003\046\006\050\001\002\000\010" +
    "\003\ufffc\006\ufffc\023\044\001\002\000\004\005\020\001" +
    "\002\000\010\003\011\013\012\014\013\001\002\000\004" +
    "\023\016\001\002\000\004\023\015\001\002\000\004\023" +
    "\014\001\002\000\004\005\ufffa\001\002\000\004\005\ufffb" +
    "\001\002\000\004\005\ufff9\001\002\000\010\003\ufffe\006" +
    "\ufffe\012\037\001\002\000\006\003\021\020\022\001\002" +
    "\000\004\023\035\001\002\000\006\011\024\022\023\001" +
    "\002\000\004\025\033\001\002\000\010\017\ufff3\021\ufff3" +
    "\024\ufff3\001\002\000\006\021\ufff5\024\ufff5\001\002\000" +
    "\006\021\030\024\027\001\002\000\006\011\024\022\023" +
    "\001\002\000\004\023\031\001\002\000\010\003\ufff8\006" +
    "\ufff8\012\ufff8\001\002\000\006\021\ufff6\024\ufff6\001\002" +
    "\000\004\022\034\001\002\000\010\017\ufff4\021\ufff4\024" +
    "\ufff4\001\002\000\010\003\ufff7\006\ufff7\012\ufff7\001\002" +
    "\000\006\003\ufffd\006\ufffd\001\002\000\006\003\040\025" +
    "\041\001\002\000\004\023\043\001\002\000\004\023\042" +
    "\001\002\000\006\003\uffdb\006\uffdb\001\002\000\006\003" +
    "\uffda\006\uffda\001\002\000\004\002\uffff\001\002\000\012" +
    "\003\ufff1\007\ufff1\010\112\025\ufff1\001\002\000\010\003" +
    "\ufff0\007\ufff0\025\ufff0\001\002\000\010\003\uffe8\007\uffe8" +
    "\025\056\001\002\000\006\003\051\025\052\001\002\000" +
    "\004\023\054\001\002\000\004\023\053\001\002\000\012" +
    "\003\uffed\007\uffed\010\uffed\025\uffed\001\002\000\012\003" +
    "\uffec\007\uffec\010\uffec\025\uffec\001\002\000\010\003\uffe9" +
    "\007\uffe9\025\056\001\002\000\004\015\074\001\002\000" +
    "\006\003\062\007\064\001\002\000\010\003\uffe6\007\uffe6" +
    "\025\uffe6\001\002\000\004\002\000\001\002\000\004\002" +
    "\uffe0\001\002\000\004\002\uffe1\001\002\000\006\003\065" +
    "\025\066\001\002\000\004\023\073\001\002\000\006\023" +
    "\uffdc\024\uffdc\001\002\000\006\023\071\024\070\001\002" +
    "\000\004\025\072\001\002\000\004\002\uffdf\001\002\000" +
    "\006\023\uffdd\024\uffdd\001\002\000\004\002\uffde\001\002" +
    "\000\004\025\075\001\002\000\006\003\076\016\077\001" +
    "\002\000\004\023\106\001\002\000\006\011\024\022\023" +
    "\001\002\000\006\017\uffe2\024\uffe2\001\002\000\006\017" +
    "\103\024\102\001\002\000\006\011\024\022\023\001\002" +
    "\000\004\023\104\001\002\000\010\003\uffe5\007\uffe5\025" +
    "\uffe5\001\002\000\006\017\uffe3\024\uffe3\001\002\000\010" +
    "\003\uffe4\007\uffe4\025\uffe4\001\002\000\010\003\uffe7\007" +
    "\uffe7\025\uffe7\001\002\000\012\003\uffee\007\uffee\010\uffee" +
    "\025\uffee\001\002\000\012\003\ufff2\007\ufff2\010\112\025" +
    "\ufff2\001\002\000\006\003\113\025\114\001\002\000\004" +
    "\023\116\001\002\000\004\023\115\001\002\000\012\003" +
    "\uffeb\007\uffeb\010\uffeb\025\uffeb\001\002\000\012\003\uffea" +
    "\007\uffea\010\uffea\025\uffea\001\002\000\012\003\uffef\007" +
    "\uffef\010\uffef\025\uffef\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\116\000\010\002\003\003\004\007\006\001\001\000" +
    "\002\001\001\000\006\004\046\012\044\001\001\000\002" +
    "\001\001\000\004\010\016\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\015" +
    "\035\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\016\025\020\024\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\020\031" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\014\107\022\110\001\001\000\002\001" +
    "\001\000\010\005\056\011\057\023\054\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\011\106\001\001\000\002" +
    "\001\001\000\006\006\060\013\062\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\017\066\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\020\077\021\100" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\020" +
    "\104\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\014\116\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public List<ErrorLSSL> errors = new ArrayList<>();
    public List<SimboloDSL> symbols = new ArrayList<>();
    
    private Token tokenAnterior = null;
    private Token tokenActual = null;
    private String automatonType = null;
    private String initialState = null;

    @Override
    public Symbol scan() throws java.lang.Exception {
        Symbol sym = super.scan();
        if (sym != null && sym.value instanceof Token) {
            tokenAnterior = tokenActual;
            tokenActual = (Token) sym.value;
        }
        return sym;
    }

    public void addSymbol(String name, String type, Token t) {
        symbols.add(new SimboloDSL(name, type, t == null ? 0 : t.getLine(), t == null ? 0 : t.getColumn()));
    }

    public void syntax_error(Symbol s) {
        Token t = (Token) s.value;
        if (t != null) {
            String lexema = t.getLexeme();
            if (tokenAnterior != null) {
                String desc = "[SinError 010] Error Sintáctico: Token inesperado '" + lexema + 
                              "'. ¿Falta un punto y coma (;) después de '" + tokenAnterior.getLexeme() + "'?";
                errors.add(new ErrorLSSL(1, desc, tokenAnterior));
            } else {
                errors.add(new ErrorLSSL(1, "[SinError 010] Error Sintáctico: Token inesperado '" + lexema + "'", t));
            }
        }
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        Token t = (Token) s.value;
        if (t != null) {
            errors.add(new ErrorLSSL(1, "[SinError 011] Error Fatal: No se pudo recuperar cerca de '" + t.getLexeme() + "'", t));
        } else {
            errors.add(new ErrorLSSL(1, "[SinError 011] Error Fatal: Fin de archivo inesperado", null));
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ASTNode start_val = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Program ::= ConfigSection StateDeclarationSection TransitionSection AcceptanceSection 
            {
              ASTNode RESULT =null;
		int cfgleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int cfgright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		ASTNode cfg = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int stsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int stsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ASTNode sts = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int trsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int trsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ASTNode trs = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int accleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int accright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode acc = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
        ASTNode root = new ASTNode("AutomataDSL_Program");
        root.addChild(cfg);
        root.addChild(sts);
        root.addChild(trs);
        root.addChild(acc);
        RESULT = root;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= error PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		
        parser.errors.add(new ErrorLSSL(1, "[SemError 100] Estructura de programa mal formada", null));
        RESULT = new ASTNode("Error_Program");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // ConfigSection ::= ConfigType AlphabetDef 
            {
              ASTNode RESULT =null;
		int ctleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int ctright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ASTNode ct = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int ableft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int abright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode ab = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ASTNode node = new ASTNode("Config_Section");
        node.addChild(ct);
        node.addChild(ab);
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConfigSection",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // ConfigSection ::= ConfigType AlphabetDef BackgroundDef 
            {
              ASTNode RESULT =null;
		int ctleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int ctright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ASTNode ct = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int ableft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int abright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ASTNode ab = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int bgleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bgright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode bg = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ASTNode node = new ASTNode("Config_Section");
        node.addChild(ct);
        node.addChild(ab);
        node.addChild(bg);
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConfigSection",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // ConfigSection ::= error 
            {
              ASTNode RESULT =null;
		
        parser.errors.add(new ErrorLSSL(1, "[SemError 101] Falta TIPO y ALFABETO al inicio del programa", null));
        RESULT = new ASTNode("Error_Config");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConfigSection",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // ConfigType ::= TIPO AFD PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 
        parser.addSymbol("AFD", "Tipo_Automata_AFD", (Token)a);
        parser.automatonType = "AFD";
        RESULT = new ASTNode("ConfigType", "AFD");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConfigType",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // ConfigType ::= TIPO AFN PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 
        parser.addSymbol("AFN", "Tipo_Automata_AFN", (Token)a);
        parser.automatonType = "AFN";
        RESULT = new ASTNode("ConfigType", "AFN");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConfigType",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // ConfigType ::= TIPO error PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		 
        parser.errors.add(new ErrorLSSL(1, "[SinError 012] Después de TIPO solo va AFD o AFN. Ejemplo: TIPO AFD;", tokenAnterior));
        RESULT = new ASTNode("ConfigType", "ERROR");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConfigType",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // AlphabetDef ::= ALFABETO LLAVE_IZQ SymbolList LLAVE_DER PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ASTNode sl = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 
        ASTNode node = new ASTNode("AlphabetDefinition");
        node.addChild(sl);
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AlphabetDef",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // AlphabetDef ::= ALFABETO error PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		
        parser.errors.add(new ErrorLSSL(1, "[SinError 013] ALFABETO debe ir: ALFABETO { 'a', 'b', ... };", tokenAnterior));
        RESULT = new ASTNode("AlphabetDefinition", "ERROR");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AlphabetDef",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SymbolList ::= SymbolList COMA SymbolVal 
            {
              ASTNode RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ASTNode sl = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        sl.addChild(s);
        RESULT = sl;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SymbolList",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SymbolList ::= SymbolVal 
            {
              ASTNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ASTNode node = new ASTNode("SymbolList");
        node.addChild(s);
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SymbolList",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // SymbolVal ::= COMILLA_SIMPLE IDENTIFICADOR COMILLA_SIMPLE 
            {
              ASTNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 
        Token t = (Token)id;
        parser.addSymbol(t.getLexeme(), "Alphabet_Symbol", t);
        RESULT = new ASTNode("Symbol", t.getLexeme());
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SymbolVal",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // SymbolVal ::= EPSILON 
            {
              ASTNode RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 
        parser.addSymbol("EPSILON", "Epsilon_Symbol", (Token)e);
        RESULT = new ASTNode("Symbol", "EPSILON");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("SymbolVal",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // StateDeclarationSection ::= StartDef StateDeclarationList 
            {
              ASTNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sdlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sdlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode sdl = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ASTNode node = new ASTNode("State_Declaration_Section");
        node.addChild(s);
        node.addChild(sdl);
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("StateDeclarationSection",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // StateDeclarationSection ::= StartDef 
            {
              ASTNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ASTNode node = new ASTNode("State_Declaration_Section");
        node.addChild(s);
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("StateDeclarationSection",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // StateDeclarationSection ::= error 
            {
              ASTNode RESULT =null;
		
        parser.errors.add(new ErrorLSSL(1, "[SemError 102] Falta INICIO <estado>;", null));
        RESULT = new ASTNode("State_Declaration_Section", "ERROR");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("StateDeclarationSection",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // StateDeclarationList ::= StateDeclarationList StateDef 
            {
              ASTNode RESULT =null;
		int sdlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sdlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ASTNode sdl = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int stleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int stright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode st = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        sdl.addChild(st);
        RESULT = sdl;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("StateDeclarationList",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // StateDeclarationList ::= StateDef 
            {
              ASTNode RESULT =null;
		int stleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int stright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode st = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ASTNode node = new ASTNode("StateList");
        node.addChild(st);
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("StateDeclarationList",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // StartDef ::= INICIO IDENTIFICADOR PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        Token t = (Token)id;
        parser.addSymbol(t.getLexeme(), "Initial_State", t);
        parser.initialState = t.getLexeme();
        RESULT = new ASTNode("StartState", t.getLexeme());
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("StartDef",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // StartDef ::= INICIO error PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		
        parser.errors.add(new ErrorLSSL(1, "[SinError 015] Formato: INICIO <estado>;", tokenAnterior));
        RESULT = new ASTNode("StartState", "ERROR");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("StartDef",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // StateDef ::= ESTADO IDENTIFICADOR PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        Token t = (Token)id;
        parser.addSymbol(t.getLexeme(), "State_Declared", t);
        RESULT = new ASTNode("StateDecl", t.getLexeme());
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("StateDef",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // StateDef ::= ESTADO error PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		
        parser.errors.add(new ErrorLSSL(1, "[SinError 016] Formato: ESTADO <nombre>;", tokenAnterior));
        RESULT = new ASTNode("StateDecl", "ERROR");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("StateDef",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // TransitionSection ::= TransitionList 
            {
              ASTNode RESULT =null;
		int tlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode tl = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ASTNode node = new ASTNode("Transition_Section");
        node.addChild(tl);
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TransitionSection",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // TransitionSection ::= 
            {
              ASTNode RESULT =null;
		
        RESULT = new ASTNode("Transition_Section");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TransitionSection",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // TransitionList ::= TransitionList Transition 
            {
              ASTNode RESULT =null;
		int tlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int tlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ASTNode tl = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode t = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        tl.addChild(t);
        RESULT = tl;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TransitionList",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // TransitionList ::= Transition 
            {
              ASTNode RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode t = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ASTNode node = new ASTNode("TransitionList");
        node.addChild(t);
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TransitionList",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // Transition ::= IDENTIFICADOR FLECHA IDENTIFICADOR CORCHETE_IZQ TransitionSymbolList CORCHETE_DER PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		int origenleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int origenright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		Object origen = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int destinoleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int destinoright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Object destino = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int tslleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tslright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ASTNode tsl = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
        Token tOri = (Token)origen;
        Token tDes = (Token)destino;
        ASTNode node = new ASTNode("Transition");
        node.addChild(new ASTNode("From", tOri.getLexeme()));
        node.addChild(new ASTNode("To", tDes.getLexeme()));
        node.addChild(tsl);
        parser.addSymbol(tOri.getLexeme() + "->" + tDes.getLexeme(), "Transition_Used", tOri);
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Transition",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // Transition ::= IDENTIFICADOR FLECHA IDENTIFICADOR error PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		int origenleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int origenright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Object origen = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int destinoleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int destinoright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object destino = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
        Token tOri = (Token)origen;
        parser.errors.add(new ErrorLSSL(1, "[SinError 014] Transición mal: " + tOri.getLexeme() + " -> dest ['símbolo'];", tOri));
        RESULT = new ASTNode("Transition", "ERROR");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Transition",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // TransitionSymbolList ::= TransitionSymbolList COMA SymbolVal 
            {
              ASTNode RESULT =null;
		int tslleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tslright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ASTNode tsl = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        tsl.addChild(s);
        RESULT = tsl;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TransitionSymbolList",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // TransitionSymbolList ::= SymbolVal 
            {
              ASTNode RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode s = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ASTNode node = new ASTNode("TransitionSymbols");
        node.addChild(s);
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TransitionSymbolList",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // AcceptanceSection ::= FinalDef 
            {
              ASTNode RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ASTNode f = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ASTNode node = new ASTNode("Acceptance_Section");
        node.addChild(f);
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AcceptanceSection",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // AcceptanceSection ::= error 
            {
              ASTNode RESULT =null;
		
        parser.errors.add(new ErrorLSSL(1, "[SemError 103] Falta FINAL <estado> [, <estado>, ...];", null));
        RESULT = new ASTNode("Acceptance_Section", "ERROR");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("AcceptanceSection",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // FinalDef ::= FINAL StateList PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ASTNode sl = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        ASTNode node = new ASTNode("FinalStates");
        node.addChild(sl);
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("FinalDef",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // FinalDef ::= FINAL error PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		
        parser.errors.add(new ErrorLSSL(1, "[SinError 017] Formato: FINAL <estado> [, <estado>, ...];", tokenAnterior));
        RESULT = new ASTNode("FinalStates", "ERROR");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("FinalDef",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // StateList ::= StateList COMA IDENTIFICADOR 
            {
              ASTNode RESULT =null;
		int slleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ASTNode sl = (ASTNode)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        Token t = (Token)id;
        parser.addSymbol(t.getLexeme(), "Final_State", t);
        sl.addChild(new ASTNode("FinalState", t.getLexeme()));
        RESULT = sl;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("StateList",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // StateList ::= IDENTIFICADOR 
            {
              ASTNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        Token t = (Token)id;
        parser.addSymbol(t.getLexeme(), "Final_State", t);
        ASTNode node = new ASTNode("StateList");
        node.addChild(new ASTNode("FinalState", t.getLexeme()));
        RESULT = node;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("StateList",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // BackgroundDef ::= FONDO IDENTIFICADOR PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        Token t = (Token)id;
        parser.addSymbol(t.getLexeme(), "Background_Color", t);
        RESULT = new ASTNode("BackgroundColor", t.getLexeme());
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("BackgroundDef",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // BackgroundDef ::= FONDO error PUNTO_Y_COMA 
            {
              ASTNode RESULT =null;
		
        parser.errors.add(new ErrorLSSL(1, "[SinError 018] Formato: FONDO <color>;", tokenAnterior));
        RESULT = new ASTNode("BackgroundColor", "ERROR");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("BackgroundDef",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
