
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLA_SIMPLE = 16;
  public static final int AFN = 10;
  public static final int COLOR = 20;
  public static final int FLECHA = 11;
  public static final int AFD = 9;
  public static final int TIPO = 2;
  public static final int ALFABETO = 3;
  public static final int COMA = 18;
  public static final int EOF = 0;
  public static final int FONDO = 8;
  public static final int CORCHETE_IZQ = 12;
  public static final int EPSILON = 7;
  public static final int CORCHETE_DER = 13;
  public static final int FINAL = 5;
  public static final int ERROR = 1;
  public static final int IDENTIFICADOR = 19;
  public static final int LLAVE_IZQ = 14;
  public static final int LLAVE_DER = 15;
  public static final int ESTADO = 6;
  public static final int PUNTO_Y_COMA = 17;
  public static final int INICIO = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TIPO",
  "ALFABETO",
  "INICIO",
  "FINAL",
  "ESTADO",
  "EPSILON",
  "FONDO",
  "AFD",
  "AFN",
  "FLECHA",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "COMILLA_SIMPLE",
  "PUNTO_Y_COMA",
  "COMA",
  "IDENTIFICADOR",
  "COLOR"
  };
}

